In [1]:
import os
import numpy as np
import pandas as pd
import geopandas as gpd
import earthpy as et 

# Set worling dir & get data
os.chdir('E:\Coding\Python\Earth Data Analytics')

In [5]:
# Import roads shapefile
sjer_roads_path = os.path.join("data", "spatial-vector-lidar", "california", 
                               "madera-county-roads", "tl_2013_06039_roads.shp")
sjer_roads = gpd.read_file(sjer_roads_path)

type(sjer_roads)
sjer_roads.head(10)

,LINEARID,FULLNAME,RTTYP,MTFCC,geometry
0,110454239066,N 14th St,M,S1400,"LINESTRING (-120.27227 37.11615, -120.27244 37..."
1,110454239052,N 11th St,M,S1400,"LINESTRING (-120.26788 37.11667, -120.26807 37..."
2,110454239056,N 12th St,M,S1400,"LINESTRING (-120.27053 37.11749, -120.27045 37..."
3,110454239047,N 10th St,M,S1400,"LINESTRING (-120.26703 37.11735, -120.26721 37..."
4,110454243091,N Westberry Blvd,M,S1400,"LINESTRING (-120.10122 36.96524, -120.10123 36..."
5,110454241495,N Schnoor St,M,S1400,"LINESTRING (-120.08765 36.98185, -120.08766 36..."
6,110454241488,N Schnoor Ave,M,S1400,"LINESTRING (-120.08313 36.95278, -120.08314 36..."
7,110454241494,N Schnoor St,M,S1400,"LINESTRING (-120.08313 36.95278, -120.08314 36..."
8,110454238495,N G St,M,S1400,"LINESTRING (-120.06160 36.96057, -120.06179 36..."
9,110454238497,N H St,M,S1400,"LINESTRING (-120.06442 36.96173, -120.06462 36..."

In [3]:
sjer_roads.isnull().sum()

LINEARID       0
FULLNAME    5149
RTTYP       5149
MTFCC          0
geometry       0
dtype: int64

In [6]:
# View data type 
print(type(sjer_roads['RTTYP']))

# View unique attributes for each road in the data
print(sjer_roads['RTTYP'].unique())

<class 'pandas.core.series.Series'>
['M' None 'S' 'C']

In [7]:
sjer_roads.head()

,LINEARID,FULLNAME,RTTYP,MTFCC,geometry
0,110454239066,N 14th St,M,S1400,"LINESTRING (-120.27227 37.11615, -120.27244 37..."
1,110454239052,N 11th St,M,S1400,"LINESTRING (-120.26788 37.11667, -120.26807 37..."
2,110454239056,N 12th St,M,S1400,"LINESTRING (-120.27053 37.11749, -120.27045 37..."
3,110454239047,N 10th St,M,S1400,"LINESTRING (-120.26703 37.11735, -120.26721 37..."
4,110454243091,N Westberry Blvd,M,S1400,"LINESTRING (-120.10122 36.96524, -120.10123 36..."